name: CI

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build with async-std
        run: cargo build --all --verbose
      - name: Build with tokio
        run: cargo build --all --features runtime-tokio --no-default-features --verbose
      - name: Run tests with async-std
        run: cargo test --all --verbose
      - name: Run tests with tokio
        run: cargo test --all --verbose --features runtime-tokio --no-default-features --verbose
